# .github/workflows/daily_video.yml
name: Daily Video Automation

on:
  # Runs every day at 10:00 AM UTC (adjust time to your preference)
  schedule:
    - cron: '0 10 * * *' 
  
  # Allows manual triggering from the Actions tab (recommended for testing)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Install FFmpeg (Required for MoviePy to write video files)
      - name: Install FFmpeg for video processing
        # 'sudo' is needed to install system packages on the runner
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 2. CRITICAL: DECODES THE YOUTUBE REFRESH TOKEN
      # This fixes all JSON and corruption errors by decoding the Base64 secret 
      # and saving it as a clean local file for Python to read.
      - name: Create Auth File for Python
        id: create_auth_file
        run: |
          # The command decodes the Base64 string from the secret and saves it as auth_token.json
          echo "${{ secrets.YOUTUBE_REFRESH_TOKEN_FILE }}" | base64 --decode > auth_token.json
        shell: bash
        
      # 3. RUN MAIN SCRIPT (Injects all secrets as environment variables)
      - name: Run Video Generation Script
        run: python main.py
        env:
          # Passes the path to the newly created token file
          YOUTUBE_TOKEN_PATH: auth_token.json
          
          # Passes the other required secrets
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
          HF_TOKEN: ${{ secrets.HF_TOKEN }}